server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    # 这里是动态路由写法
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/getPaymentEntity/**   # 断言,路径相匹配的进行路由
        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          filters:
            # 过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
            - AddRequestParameter=X-Request-Id,1024
          predicates:
            - Path=/payment/lb   # 断言,路径相匹配的进行路由
        - id: payment_routh3
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/discovery   # 断言,路径相匹配的进行路由


# 下面是 静态的，写死的路由
#    gateway:
#      routes:
#        - id: payment_routh   # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   # 匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/getPaymentEntity/**   # 断言,路径相匹配的进行路由
#
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/discovery/   # 断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


